name: iOS - Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Homebrew
        run: |
          brew update
          brew install xcodegen || true

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Xcode version
        run: xcodebuild -version

      - name: Build (Debug)
        run: xcodebuild -project ExpenseTracker.xcodeproj -scheme ExpenseTracker -destination 'generic/platform=iOS' -configuration Debug build | xcpretty || true


