name: iOS - Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Homebrew
        run: |
          brew update
          brew install xcodegen || true
          sudo gem install xcpretty --no-document

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Xcode version
        run: xcodebuild -version

      - name: Show project schemes/targets
        run: xcodebuild -list -project ExpenseTracker.xcodeproj | cat

      - name: Show available SDKs
        run: xcodebuild -showsdks | cat

      - name: Build (Debug, no signing)
        run: |
          set -o pipefail
          xcodebuild -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -destination 'generic/platform=iOS' \
            -configuration Debug \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO \
            -resultBundlePath build/ResultBundle \
            build | tee build/build.log

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-build-artifacts
          path: |
            build/build.log
            build/ResultBundle.xcresult


