name: iOS - Export Signed IPA

on:
  workflow_dispatch:
    inputs:
      team_id:
        description: 'Apple Developer Team ID'
        required: true
        type: string
      bundle_id:
        description: 'App Bundle ID'
        required: true
        type: string
        default: 'com.example.expensetracker'

jobs:
  export-ipa:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Homebrew
        run: |
          brew update
          brew install xcodegen || true
          sudo gem install xcpretty --no-document

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Update Bundle ID
        run: |
          # Update the bundle ID in project.yml
          sed -i '' "s/com.example.expensetracker/${{ github.event.inputs.bundle_id }}/g" project.yml
          xcodegen generate

      - name: Create Export Options Plist
        run: |
          cat > ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>${{ github.event.inputs.team_id }}</string>
              <key>compileBitcode</key>
              <false/>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>thinning</key>
              <string>&lt;none&gt;</string>
          </dict>
          </plist>
          EOF

      - name: Archive App
        run: |
          set -o pipefail
          xcodebuild -project ExpenseTracker.xcodeproj \
            -scheme ExpenseTracker \
            -destination 'generic/platform=iOS' \
            -configuration Release \
            -archivePath build/ExpenseTracker.xcarchive \
            -allowProvisioningUpdates \
            archive | tee build/archive.log

      - name: Export IPA
        run: |
          set -o pipefail
          xcodebuild -exportArchive \
            -archivePath build/ExpenseTracker.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            -allowProvisioningUpdates | tee build/export.log

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ExpenseTracker-IPA
          path: build/ipa/*.ipa
          retention-days: 30

      - name: Upload Build Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build/archive.log
            build/export.log
